In [12]:
from cvxopt import matrix
from cvxopt.solvers import lp
import numpy as np

In [18]:
c = [90, 100, -5, -20, -20]
s = [[0,    0,  15,  15],
     [0,   15,   0,    5],
     [15,   0,   0,    0],
     [0,   15,   0,    0],
     [0,    0,   5,    0]]

In [47]:
n = 5

In [55]:
cc = matrix(-1 * np.array(c, dtype=np.float))

B = np.concatenate((np.eye(2), np.zeros((3, 2))))
C = [[1, 1, 1],
     [0, 1, 1]]
D = np.concatenate((C, -1 * np.eye(3)))

G = matrix(np.concatenate((B, s, -1 * np.eye(n), D), axis=1).T)
h = matrix(np.concatenate(([100, 50, 2400, 2400, 2400, 2400], np.zeros(3 + 5))).T)

sol = lp(cc, G, h)

     pcost       dcost       gap    pres   dres   k/t
 0: -1.3075e+04 -1.2289e+05  3e+04  1e-01  4e+00  1e+00
 1: -6.5453e+03 -2.0555e+05  2e+05  2e-01  7e+00  3e+03
 2: -7.5079e+03 -3.8021e+04  1e+04  3e-02  1e+00  3e+03
 3: -6.2821e+03 -1.0220e+04  9e+02  4e-03  1e-01  3e+02
 4: -6.3640e+03 -8.2463e+03  6e+02  2e-03  7e-02  1e+02
 5: -6.2902e+03 -6.5380e+03  9e+01  2e-04  8e-03  5e+00
 6: -6.2999e+03 -6.3027e+03  1e+00  3e-06  9e-05  5e-02
 7: -6.3000e+03 -6.3000e+03  1e-02  3e-08  9e-07  5e-04
 8: -6.3000e+03 -6.3000e+03  1e-04  3e-10  9e-09  5e-06
Optimal solution found.


In [56]:
print(sol['x'])

[ 1.00e+02]
[ 3.00e+01]
[ 1.00e+02]
[ 1.30e+02]
[ 1.30e+02]



In [58]:
print(G)

[ 1.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  1.00e+00  0.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  1.50e+01  0.00e+00  0.00e+00]
[ 0.00e+00  1.50e+01  0.00e+00  1.50e+01  0.00e+00]
[ 1.50e+01  0.00e+00  0.00e+00  0.00e+00  5.00e+00]
[ 1.50e+01  5.00e+00  0.00e+00  0.00e+00  0.00e+00]
[-1.00e+00 -0.00e+00 -0.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -1.00e+00 -0.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -1.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -0.00e+00 -1.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -0.00e+00 -0.00e+00 -1.00e+00]
[ 1.00e+00  0.00e+00 -1.00e+00 -0.00e+00 -0.00e+00]
[ 1.00e+00  1.00e+00 -0.00e+00 -1.00e+00 -0.00e+00]
[ 1.00e+00  1.00e+00 -0.00e+00 -0.00e+00 -1.00e+00]

