In [1]:
from matplotlib import pyplot as plt
import numpy as np
from tqdm import tqdm
import time
from scipy import optimize
%matplotlib inline

In [2]:
np.random.seed = 420

# Gradient descent method
Since matrix $P$ is given in the problem statement, we will set it uniformly distributed. Let $n = 4$ and $m = 5$.

In [3]:
n = 4
m = 5
P = np.array([np.random.uniform(size=n) for x in np.zeros(m)])
P /= P.sum(axis=0)
c_t = np.array([-np.sum(x * np.log2(x)) for x in P.T])
print(P)

[[0.07080633 0.11537703 0.22002895 0.2811566 ]
 [0.22490138 0.39550501 0.00420416 0.03564955]
 [0.23184261 0.00372862 0.26632326 0.29489023]
 [0.20151782 0.03636117 0.21661156 0.3463133 ]
 [0.27093187 0.44902816 0.29283207 0.04199032]]


In [4]:
def f(x):
    #get projection of x
    x_ = euclidean_proj_simplex(x)
    y = P @ x_
    if (np.min(y) <= 0):
        return np.inf
    return c_t @ x_ + np.sum(y * np.log(y) / np.log(2))

def grad_f(x):
    #get projection of x
    x_ = euclidean_proj_simplex(x)
    y = P @ x_
    if (np.min(y) <= 0):
        raise ValueError
    grad = c_t.copy()
    tmp = []
    for i in range(m):
        tmp.append(P[i] * (np.log(P[i] @ x_) + 1) / np.log(2))
    tmp_sum = np.sum(np.array(tmp), axis=0)
    return grad + tmp_sum

def gess_f(x):
    x_ = euclidean_proj_simplex(x)
    y = P @ x_
    if (np.min(y) <= 0):
        raise ValueError
    gess = []
    for i in range(m):
        tmp = np.atleast_2d(P[i]).T @ np.atleast_2d(P[i])
        gess.append(tmp / (y[i] * np.log(2)))
    return np.sum(np.array(gess), axis=0)

In [5]:
def euclidean_proj_simplex(v, s=1):
    n, = v.shape  
    if v.sum() == s and np.alltrue(v >= 0):
        return v
    u = np.sort(v)[::-1]
    cssv = np.cumsum(u)
    rho = np.nonzero(u * np.arange(1, n+1) > (cssv - s))[0][-1]
    theta = (cssv[rho] - s) / (rho + 1.0)
    w = (v - theta).clip(min=0)
    return w

In [6]:
class StoppingCriteria:
    def __init__(self, max_iterations=np.inf, min_grad_norm=0):
        self.max_iterations = max_iterations
        self.min_grad_norm = min_grad_norm
    
    def __call__(self, state):
        cur_iterations = state['iterations']
        cur_grad_norm = np.linalg.norm(state['cur_grad'], ord=2)
        dif_x = np.linalg.norm(state['x'] - state['prev_x'], ord=2)
        return (cur_iterations >= self.max_iterations or 
                cur_grad_norm <= self.min_grad_norm or dif_x <= self.min_grad_norm)
    
class StoppingCriteriaNewton:
    def __init__(self, max_iterations=np.inf, tolerance=10**(-4), min_grad_norm=0):
        self.max_iterations = max_iterations
        self.tolerance = tolerance
        self.min_grad_norm = min_grad_norm
    
    def __call__(self, state):
        cur_iterations = state['iterations']
        dif_x = np.linalg.norm(state['x'] - state['prev_x'], ord=2)
        cur_decrement = state['cur_grad'].T @ state['cur_gess_inv'] @ state['cur_grad']
        return (cur_iterations >= self.max_iterations or 
                cur_decrement/2 <= self.tolerance or dif_x <= self.min_grad_norm)

In [7]:
class StepSearchFastestTernary:
    def __init__(self, precision):
        self.precision = precision
        self.left = 0
        self.right = None
        
    def __update_starting_points(self, state, init_kpower=-2):
        k_power = init_kpower
        f = state['f']
        x = state['x']
        grad_f = state['cur_grad']
        dx = - grad_f
        while f(x + 2**k_power * dx) > f(x + 2**(k_power + 1) * dx):
            k_power += 1
        if k_power == init_kpower:
            self.left = 0
        else:
            self.left = 2**(k_power - 1)
        self.right = 2**(k_power + 1)
            
            
    def __call__(self, state):
        f = state['f']
        x = state['x']
        cur_grad = state['cur_grad']
        dx = -cur_grad
        
        self.__update_starting_points(state) # update self.left and self.right
        
        right = self.right
        left = self.left
        
        while True:
            if abs(right - left) < self.precision:
                return (left + right)/2

            left_div = left + (right - left)/3
            right_div = right - (right - left)/3

            f_left = f(x + left_div * dx)
            f_right = f(x + right_div * dx)
            
            if f_left == np.inf:
                right = right_div
            else:
                if f_left < f_right:
                    right = right_div
                else:
                    left = left_div
        

In [8]:
class GradientDescentMethod:
    def __init__(self, t_search, stopping_criteria):
        self.t_search = t_search
        self.stopping_criteria = stopping_criteria
    
    def fit(self, f, grad_f, x_0):
        x = x_0.copy()
        state = dict()
        state['f'] = f
        state['grad_f'] = grad_f
        state['x'] = x
        # hardcoded xD
        state['prev_x'] = np.ones(n) / n
        
        state['iterations'] = 0
        state['time'] = time.time()
        while True:
            state['cur_grad'] = grad_f(state['x'])
            if self.stopping_criteria(state):
                break
            t = self.t_search(state)
            state['prev_x'] = state['x'].copy()
            state['x'] -= t * state['cur_grad']
            #take projection on simplex
            state['x'] = euclidean_proj_simplex(state['x'])
            state['iterations'] += 1
            
        state['time'] = time.time() - state['time']
        return state

In [9]:
class NewtonMethod:
    def __init__(self, t_search, stopping_criteria):
        self.t_search = t_search
        self.stopping_criteria = stopping_criteria
    
    def fit(self, f, grad_f, gess_f, x_0):
        x = x_0.copy()
        state = dict()
        state['f'] = f
        state['grad_f'] = grad_f
        state['x'] = x
        # hardcoded xD
        state['prev_x'] = np.ones(n) / n
        
        state['iterations'] = 0
        state['time'] = time.time()
        while True:
            state['cur_grad'] = grad_f(state['x'])
            state['cur_gess'] = gess_f(state['x'])
            state['cur_gess_inv'] = np.linalg.inv(state['cur_gess'])

            if self.stopping_criteria(state):
                break
                
            step = -state['cur_gess_inv'] @ grad_f(state['x'])
            t = self.t_search(state)
            state['prev_x'] = state['x'].copy()
            state['x'] += t * step
            #take projection on simplex
            state['x'] = euclidean_proj_simplex(state['x'])
            state['iterations'] += 1
            
        state['time'] = time.time() - state['time']
        return state

In [10]:
stopping_criteria = StoppingCriteria(min_grad_norm=1e-7)
t_search = StepSearchFastestTernary(precision=1e-7)
grad = GradientDescentMethod(t_search=t_search, stopping_criteria=stopping_criteria)
x_0 = np.random.uniform(low=0, high=1, size=n)
x_0 /= np.sum(x_0)
state = grad.fit(f, grad_f, x_0)
print('x_0 = ', x_0)
print('f_min =', f(state['x']))
print('time = ', state['time'])
print('x = ',state['x'])

x_0 =  [0.2824378  0.19136063 0.40211072 0.12409085]
f_min = -0.534234052467002
time =  0.02068614959716797
x =  [0.         0.50339697 0.         0.49660303]


In [11]:
stopping_criteria = StoppingCriteriaNewton(max_iterations=10**3)
t_search = StepSearchFastestTernary(precision=1e-7)
newton = NewtonMethod(t_search=t_search, stopping_criteria=stopping_criteria)
state = newton.fit(f, grad_f, gess_f, x_0)
print('x_0 = ', x_0)
print('f_min =', f(state['x']))
print('time = ', state['time'])
print('x = ',state['x'])

x_0 =  [0.2824378  0.19136063 0.40211072 0.12409085]
f_min = -0.532982717694676
time =  0.0819556713104248
x =  [0.         0.47697571 0.         0.52302429]


In [12]:
cons = ({'type': 'eq', 'fun': lambda x:  np.sum(x) - 1},
        {'type': 'ineq', 'fun': lambda x: x[0]},
        {'type': 'ineq', 'fun': lambda x: x[1]},
       {'type': 'ineq', 'fun': lambda x: x[2]},
       {'type': 'ineq', 'fun': lambda x: x[3]})

In [13]:
print(optimize.minimize(f, x_0, method='SLSQP',
               constraints=cons))

     fun: -0.5342340524669997
     jac: array([ 2.83214331e-01,  5.96046448e-08,  1.24464795e-01, -1.49011612e-08])
 message: 'Optimization terminated successfully.'
    nfev: 36
     nit: 6
    njev: 6
  status: 0
 success: True
       x: array([-6.72205380e-18,  5.03397004e-01,  7.25598544e-18,  4.96602996e-01])
